### ISSUE TITLE
Error with composer.json

### ISSUE THREAD

**Issue by casperh1nl** [MultiSafepay/Prestashop#8]
https://github.com/MultiSafepay/PrestaShop/blob/develop/composer.json

in the composer we had set the name to "multisafepay/prestashop" Bit if you do that because of the composer installer package it gets installed in the "module/prestashop" folder instead of the folder i want.

Also i have no good idea to name the bundle right now...

**Comment by Jasper-MultiSafepay** [comment]
Hmm, you're right.
When we perform a composer require multisafepay/prestashop:dev-develop, it gets installed in the prestashop folder, instead of multisafepay.
And we cannot rename the package to multisafepay/multisafepay.

I guess we're removing the composer.json from develop, but we'll discuss this internally

**Comment by Jasper-MultiSafepay** [comment]
@casperh1nl 
Using https://github.com/composer/installers#custom-install-names this should be fixed on develop now.
See https://github.com/MultiSafepay/PrestaShop/pull/9
It installs correctly into modules/multisafepay
If you still want to have a different folder, you can take a look at https://github.com/composer/installers#custom-install-paths
